# The "App Release" workflow is manually triggered to release the application to production. It updates the version and
# changelog, creates a new tag, commits the changes, and pushes them to the repository when triggered on the main branch.

name: App Release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Setup
        uses: cgero-eth/release-test/.github/actions/setup@main
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Setup Git config
        run: |
          git config --global user.name "cgero-eth"
          git config --global user.email "ruggero.cino@gmail.com"
      - name: Update version and changelog
        run: yarn changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Create tag
        run: yarn changeset tag
      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Commit changes
        run: |
          git add --all
          git commit -am "Release v${{ steps.package-version.outputs.current-version}}"
          git push --follow-tags
