name: Release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20
  NODE_CACHE: "yarn"

jobs:
  versioning:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.NODE_CACHE }}
      - name: Setup Git config
        run: |
          git config --global user.name "cgero-eth"
          git config --global user.email "ruggero.cino@gmail.com"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Update version and changelog
        run: yarn changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Create tag
        run: yarn changeset tag
      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Commit changes
        run: |
          git add --all
          git commit -am "Release v${{ steps.package-version.outputs.current-version}}"
          git push --follow-tags

  prepare:
    runs-on: ubuntu-latest
    needs: versioning
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.NODE_CACHE }}
      - name: Build application
        run: echo "Build application"

  deploy:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.NODE_CACHE }}
      - name: Deploy application
        run: echo "Deploy application"

  release:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          ref: main
      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Read changelog updates
        id: read-changelog
        uses: actions/github-script@v7.0.1
        env:
          version: "${{ steps.package-version.outputs.current-version }}"
          path: ./CHANGELOG.md
        with:
          script: |
            const readChangelog = require('./.github/workflows/scripts/readChangelog.js');
            readChangelog({ github, context, core });
      - name: Create release
        uses: softprops/action-gh-release@v2.2.1
        with:
          prerelease: false
          tag_name: "v${{ steps.package-version.outputs.current-version}}"
          body: ${{ steps.read-changelog.outputs.changes }}
